### ISSUE TITLE
Feature request: Reset database

### ISSUE THREAD

**Issue by jakecraige** [behrendtio/monky#31]
It would be awesome if monky kept track of what it created and we could call a method to reset the database.

**Comment by behrendtio** [comment]
Hm I'm not sure if that's a good idea or not, yet. Keeping track of all the created models is certainly easy, but you could build models with monky and save them later on in your tests without monky knowing about it.

Furthermore it would increase monky's footprint quite a lot for a very "small" feature.

In general from my experience you'd want to clean the whole (test) database anyways for each run of a test don't you? What I could potentially see is either a monky feature like `monky.clearDatabase()` or a separate monky plugin.

On the other hand, clearing the database should be as simple as doing `connection.db.dropDatabase()` on the mongoose connection. So it's not really saving you any code doing it via monky instead of directly.

What do you think, did you have something else in mind?

**Comment by janckerchen** [comment]
It make sense to  only clean specific collections, not entire db, for example, I will clean 'User' collection after  register test suit.

**Comment by jakecraige** [comment]
My inspiration for this idea was this project https://github.com/DatabaseCleaner/database_cleaner It's almost unanimously used in rails testing stacks. It's pretty frustrating to have to clean out the db before every test that uses it. Once you get a larger test suite, lots of it would begin with cleaning out the test suite rather than have something you could hook into automatically to do it.

**Comment by behrendtio** [comment]
Yeah I know `database_cleaner` and use it myself quite a lot. And it's a very good example why it should *not* be a part of `monky`, but a separate module. Cleaning the user collection is fairly simple with `mongoose`, so I'm closing this as a "won't change".

I'd suggest to write a separate module just like `database_cleaner` - or a module called `monky-clean` or so, which monkey patches `monky` with something like `monky.clear()` and `monky.clear('user')`, which hooks into the respective test runner like `mocha`. Perhaps even with plugins for each test runner. So it's not a trivial thing and would totally be too much functionality for `monky`.
