### ISSUE TITLE
FR: Ability to use functions to generate a property value

### ISSUE THREAD

**Issue by yannvanhalewyn** [behrendtio/monky#33]
I would love to have Monky be able to interpolate the value of a given function on every build/create. This would make it work nicely with libraries like Chance, or other random generators to fit the need of a formatted unique field.

    monky.factory('User', {
        firstName: chance.first,    // A function that returns a random first name
        lastName: chance.last,
        provider_id: chance.string
    });

What do you think?

**Comment by behrendtio** [comment]
`Monky` already supports passing a function to factories. But the function is then bound to the model itself, so one can do things like `this.active`. See [this test](https://github.com/behrendtio/monky/blob/master/test/monky.js#L162) for more clarification.

So I'd rather not change the API for this, since otherwise you won't have clear and easy access to the model _instance_. However, you could of course wrap your function call with another function:

```
monky.factory('Address', { street: function() {
  return chance.first();
}});

monky.build('Address', function(err, address) {
  if (err) return done(address);
  console.log(address);
  done();
});
```

This protects the existing API and gives you the ability to include libraries like `chance` without much hassle. Plus you could change the `chance` call depending on the model instance's values, using the aforementioned `this.X`. E.g. using the ipv6 generator if necessary:

```
monky.factory('Domain', { ipAddress: function() {
  if (this.isIpv6) {
    return chance.ipv6()
  }

  return chance.ip();
}});
```

**Comment by yannvanhalewyn** [comment]
Thanks for responding. I did look for it, and did try it. But I supposed I looked and tried wrong, apologies. 
Cheers :+1:
